"""Simple-Dual: final Research Deliverable 1 reference implementation.

This module implements a deterministic, post-generation and model-independent
dual-layer hallucination detector for the four products in the official Sleep
Haven ``sample_product_catalog``.  It is aligned with the final RD1 design:

* sixteen independent questions (Q1-Q16), with four questions per product;
* four catalogue products and product-specific verification;
* internal within-response self-consistency detection;
* external authorised-knowledge verification;
* supported / contradicted / unsupported / omitted factual classifications;
* inclusive OR fusion and interpretable JSON diagnostics;
* automatic batch processing for the 16-question x 4-model (64-response) grid.

The RD1 implementation is restricted to Q1-Q16 independent responses and
automatic rule-based diagnostic outputs.  ROUGE and BERTScore belong to
Research Deliverable 3 and are therefore not calculated here.

The detector is a transparent rule-based research artefact, not a general
semantic or natural-language-inference model.  Its coverage is bounded by the
catalogue, concept patterns and task specifications defined in this file.
"""

from __future__ import annotations

import argparse
import csv
import json
import re
import sys
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any, Iterable, Optional


# ---------------------------------------------------------------------------
# PyCharm configuration (edit this section, then click the green Run button)
# ---------------------------------------------------------------------------

# Available modes:
#   "REFERENCE_16"   Evaluate all Q1-Q16 standard reference answers.
#   "SINGLE"         Evaluate one answer generated by a language model.
#   "CREATE_TEMPLATE"Create the 64-row Q1-Q16 x four-model CSV template.
#   "BATCH"          Evaluate all responses in a completed CSV template.
#   "SELF_TEST"      Run the detector's deterministic validation tests.
PYCHARM_MODE = "BATCH"

# Settings used when PYCHARM_MODE = "SINGLE".
PYCHARM_TASK_ID = "Q7"
PYCHARM_MODEL_ID = "demonstration-model"
PYCHARM_MODEL_ANSWER = """
The Classic Harmony Spring Mattress costs $1,299 and is available in Queen
and King sizes.
"""

# Optional alternative to PYCHARM_MODEL_ANSWER. Leave this empty to paste the
# answer above. For a Windows absolute path, use a raw string, for example:
# PYCHARM_ANSWER_FILE = r"D:\pythonProject\pythonProject4\model_answer.txt"
PYCHARM_ANSWER_FILE = ""

# Settings used by CREATE_TEMPLATE and BATCH. Relative paths are resolved from
# the Working directory configured in PyCharm's Run/Debug Configuration.
PYCHARM_TEMPLATE_PATH = "standard_64_responses.csv"
PYCHARM_BATCH_CSV_PATH = "standard_64_responses.csv"
PYCHARM_BATCH_OUTPUT_PATH = "simple_dual_rd1_results.jsonl"
PYCHARM_REQUIRE_COMPLETE_GRID = True


# ---------------------------------------------------------------------------
# Authorised product catalogue
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class ConceptDefinition:
    attribute: str
    canonical: str
    patterns: tuple[str, ...]


CONCEPTS: dict[str, ConceptDefinition] = {
    # Product 1
    "memory_foam": ConceptDefinition(
        "material", "memory foam", (r"\bmemory[- ]foam\b",)
    ),
    "temperature_sensitive_memory_foam": ConceptDefinition(
        "material",
        "temperature-sensitive memory foam",
        (r"\btemperature[- ]sensitive\s+memory[- ]foam\b",),
    ),
    "high_density_foam_base": ConceptDefinition(
        "support_base",
        "high-density foam base",
        (r"\bhigh[- ]density\s+foam\s+base\b", r"\bdense\s+foam\s+base\b"),
    ),
    "cooling_gel": ConceptDefinition(
        "temperature_control",
        "cooling gel-infused particles",
        (
            r"\bcooling\s+gel[- ]infused\s+particles\b",
            r"\bgel[- ]infused\s+particles\b",
            r"\bcooling\s+gel\b",
        ),
    ),
    "body_conforming": ConceptDefinition(
        "support",
        "conforms to the sleeper's body shape",
        (
            r"\b(?:embraces|conforms?\s+to|molds?\s+to)\s+(?:the\s+|your\s+)?body(?:'s)?\s+shape\b",
            r"\bbody[- ]conforming\b",
        ),
    ),
    "personalized_support": ConceptDefinition(
        "support", "personalized support", (r"\bpersonali[sz]ed\s+support\b",)
    ),
    "temperature_regulation": ConceptDefinition(
        "temperature_control",
        "temperature regulation",
        (
            r"\bregulates?\s+(?:the\s+|your\s+)?body\s+temperature\b",
            r"\btemperature\s+regulation\b",
            r"\bkeep(?:s|ing)?\s+(?:the\s+sleeper|you)\s+cool\b",
        ),
    ),
    "breathable_cover": ConceptDefinition(
        "cover",
        "breathable cover",
        (
            r"\bbreathable\s+(?:surface|cover)\b",
            r"\bbreathable\s+hypoallergenic\s+cover\b",
        ),
    ),
    "hypoallergenic": ConceptDefinition(
        "allergy", "hypoallergenic", (r"\bhypoallergenic\b", r"\banti[- ]allergy\b")
    ),
    "silver_thread": ConceptDefinition(
        "cover",
        "silver-thread embroidery",
        (
            r"\bsilver[- ]thread\s+embroidery\b",
            r"\bembroidered\s+with\s+silver\s+threads?\b",
            r"\bsilver\s+threads?\b",
        ),
    ),
    # Product 2
    "inner_spring": ConceptDefinition(
        "structure",
        "inner-spring construction",
        (
            r"\binner[- ]spring\s+construction\b",
            r"\binner[- ]spring\b",
            r"\bspring[- ]coil\s+(?:core|construction)\b",
            r"\bspring\s+coil\b",
            r"\bspring\s+mattress\b",
        ),
    ),
    "plush_padding": ConceptDefinition(
        "comfort", "layers of plush padding", (r"\b(?:layers?\s+of\s+)?plush\s+padding\b",)
    ),
    "quilted_top": ConceptDefinition(
        "comfort", "quilted top layer", (r"\bquilted\s+top(?:\s+layer)?\b",)
    ),
    "reinforced_edges": ConceptDefinition(
        "durability", "reinforced edges", (r"\breinforced\s+edges?\b",)
    ),
    "sag_prevention": ConceptDefinition(
        "durability",
        "prevents sagging",
        (r"\bprevent(?:s|ing)?\s+sagging\b", r"\banti[- ]sag(?:ging)?\b"),
    ),
    "natural_cotton_cover": ConceptDefinition(
        "cover", "natural cotton cover", (r"\bnatural\s+cotton\s+cover\b",)
    ),
    "moisture_wicking": ConceptDefinition(
        "moisture_control",
        "moisture-wicking",
        (
            r"\bmoisture[- ]wicking\b",
            r"\bwicks?\s+away\s+moisture\b",
            r"\bkeep(?:s|ing)?\s+(?:the\s+sleeper|you)\s+dry\b",
        ),
    ),
    # Product 3
    "natural_latex": ConceptDefinition(
        "material",
        "100% natural latex",
        (r"\b100\s*%\s+natural\s+latex\b", r"\bnatural\s+latex\b", r"\blatex\b"),
    ),
    "eco_friendly_plantations": ConceptDefinition(
        "sustainability",
        "latex harvested from eco-friendly plantations",
        (r"\beco[- ]friendly\s+plantations?\b",),
    ),
    "responsive_bouncy": ConceptDefinition(
        "comfort", "responsive and bouncy feel", (r"\bresponsive,?\s+(?:and\s+)?bouncy\b",)
    ),
    "pressure_relief": ConceptDefinition(
        "comfort", "pressure relief", (r"\bpressure\s+relief\b",)
    ),
    "pocketed_coils": ConceptDefinition(
        "structure",
        "individually pocketed coils",
        (r"\bindividually\s+pocketed\s+coils?\b", r"\bpocketed\s+coils?\b"),
    ),
    "minimal_motion_transfer": ConceptDefinition(
        "motion_transfer",
        "minimal motion transfer",
        (
            r"\bminimal\s+motion\s+transfer\b",
            r"\bminimi[sz]e(?:s|d|ing)?\s+motion\s+transfer\b",
            r"\breduces?\s+motion\s+transfer\b",
            r"\bmotion\s+isolation\b",
        ),
    ),
    "organic_cotton_cover": ConceptDefinition(
        "cover",
        "certified organic cotton cover",
        (r"\b(?:certified\s+)?organic\s+cotton\s+cover\b",),
    ),
    "antimicrobial": ConceptDefinition(
        "allergy", "natural antimicrobial properties", (r"\bantimicrobial\b",)
    ),
    # Product 4
    "adaptive_foam": ConceptDefinition(
        "support", "plush adaptive foam", (r"\bplush,?\s+adaptive\s+foam\b", r"\badaptive\s+foam\b")
    ),
    "tailored_support": ConceptDefinition(
        "support", "tailored support", (r"\btailored\s+support\b",)
    ),
    "high_resilience_support_foam": ConceptDefinition(
        "support_base",
        "high-resilience support foam",
        (r"\bhigh[- ]resilience\s+support\s+foam\b",),
    ),
    "bamboo_top": ConceptDefinition(
        "material",
        "bamboo-infused top layer",
        (r"\bbamboo[- ]infused\s+top\s+layer\b", r"\bbamboo[- ]infused\s+layer\b"),
    ),
    "cool_surface": ConceptDefinition(
        "temperature_control", "soft, cool sleeping surface", (r"\bcool\s+sleeping\s+surface\b",)
    ),
    "bamboo_breathability": ConceptDefinition(
        "moisture_control",
        "natural breathability of bamboo",
        (r"\bbamboo(?:'s)?\s+natural\s+breathability\b", r"\bnatural\s+breathability\b"),
    ),
    "removable_bamboo_cover": ConceptDefinition(
        "cover",
        "silky removable bamboo cover",
        (r"\b(?:silky,?\s+)?removable\s+bamboo\s+cover\b",),
    ),
    # Explicitly incompatible descriptions used by the logical layer.
    "heat_retaining_foam": ConceptDefinition(
        "temperature_control", "heat-retaining foam", (r"\bheat[- ]retaining\s+foam\b",)
    ),
    "unembroidered_cover": ConceptDefinition(
        "cover", "plain unembroidered cover", (r"\b(?:plain\s+)?unembroidered\s+cover\b",)
    ),
    "thin_disposable_base": ConceptDefinition(
        "support_base", "thin disposable foam base", (r"\bthin\s+disposable\s+foam(?:\s+base)?\b",)
    ),
}


@dataclass(frozen=True)
class ProductKnowledge:
    product_id: str
    name: str
    name_aliases: tuple[str, ...]
    price: int
    sizes: tuple[str, ...]
    authorised_concepts: frozenset[str]


PRODUCTS: dict[str, ProductKnowledge] = {
    "SH-LCC-MFM-001": ProductKnowledge(
        "SH-LCC-MFM-001",
        "Luxury Cloud-Comfort Memory Foam Mattress",
        ("Luxury Cloud Comfort Memory Foam Mattress",),
        999,
        ("Twin", "Queen", "King"),
        frozenset(
            {
                "memory_foam",
                "temperature_sensitive_memory_foam",
                "high_density_foam_base",
                "cooling_gel",
                "body_conforming",
                "personalized_support",
                "temperature_regulation",
                "breathable_cover",
                "hypoallergenic",
                "silver_thread",
            }
        ),
    ),
    "SH-CHSM-002": ProductKnowledge(
        "SH-CHSM-002",
        "Classic Harmony Spring Mattress",
        (),
        1299,
        ("Queen", "King"),
        frozenset(
            {
                "inner_spring",
                "plush_padding",
                "quilted_top",
                "reinforced_edges",
                "sag_prevention",
                "natural_cotton_cover",
                "moisture_wicking",
            }
        ),
    ),
    "SH-EGHL-003": ProductKnowledge(
        "SH-EGHL-003",
        "EcoGreen Hybrid Latex Mattress",
        ("Eco Green Hybrid Latex Mattress",),
        1599,
        ("Twin", "Full"),
        frozenset(
            {
                "natural_latex",
                "eco_friendly_plantations",
                "responsive_bouncy",
                "pressure_relief",
                "pocketed_coils",
                "minimal_motion_transfer",
                "organic_cotton_cover",
                "breathable_cover",
                "antimicrobial",
                "hypoallergenic",
            }
        ),
    ),
    "SH-PSBM-004": ProductKnowledge(
        "SH-PSBM-004",
        "Plush Serenity Bamboo Mattress",
        (),
        2599,
        ("King",),
        frozenset(
            {
                "adaptive_foam",
                "body_conforming",
                "tailored_support",
                "high_resilience_support_foam",
                "sag_prevention",
                "bamboo_top",
                "cool_surface",
                "temperature_regulation",
                "bamboo_breathability",
                "moisture_wicking",
                "removable_bamboo_cover",
            }
        ),
    ),
}

CATALOGUE_VERSION = "sleep-haven-four-product-2026-08"
MODEL_IDS = ("Gemini", "DeepSeek", "Doubao", "ChatGPT")


# Claims that are absent from every official product description.  Known
# product features are handled product-by-product through CONCEPTS instead.
GENERIC_UNSUPPORTED_CLAIMS: dict[str, tuple[str, ...]] = {
    "medical_treatment": (
        r"\btreats?\s+back\s+pain\b",
        r"\bcures?\s+back\s+pain\b",
        r"\bguarantees?\s+proper\s+spinal\s+alignment\b",
    ),
    "warranty": (r"\b\d+[- ]year\s+warranty\b", r"\blifetime\s+warranty\b"),
    "unsupported_suitability": (r"\bideal\s+for\s+side\s+sleepers?\b",),
}


# ---------------------------------------------------------------------------
# Balanced Q1-Q16 task specifications and standard reference answers
# Four single-turn questions are assigned to each catalogue product:
# composition, functions, price/sizes, and misleading-information correction.
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class RequiredDenial:
    kind: str  # concept | price | size
    value: Any


@dataclass(frozen=True)
class TaskSpecification:
    task_id: str
    question: str
    product_ids: tuple[str, ...]
    required_concept_groups: dict[str, tuple[tuple[str, ...], ...]] = field(default_factory=dict)
    require_price: tuple[str, ...] = ()
    require_exact_sizes: tuple[str, ...] = ()
    require_product_names: tuple[str, ...] = ()
    required_denials: dict[str, tuple[RequiredDenial, ...]] = field(default_factory=dict)


P1 = "SH-LCC-MFM-001"
P2 = "SH-CHSM-002"
P3 = "SH-EGHL-003"
P4 = "SH-PSBM-004"


TASK_SPECIFICATIONS: dict[str, TaskSpecification] = {
    "Q1": TaskSpecification(
        "Q1",
        "What materials and structural components are used in the Luxury Cloud-Comfort Memory Foam Mattress?",
        (P1,),
        required_concept_groups={
            P1: (
                ("temperature_sensitive_memory_foam",),
                ("high_density_foam_base",),
                ("cooling_gel",),
                ("breathable_cover",),
                ("hypoallergenic",),
                ("silver_thread",),
            )
        },
    ),
    "Q2": TaskSpecification(
        "Q2",
        "How does the Luxury Cloud-Comfort Memory Foam Mattress provide personalized support, temperature regulation, durability, and allergy protection?",
        (P1,),
        required_concept_groups={
            P1: (
                ("body_conforming", "personalized_support"),
                ("cooling_gel",),
                ("temperature_regulation",),
                ("high_density_foam_base",),
                ("hypoallergenic",),
            )
        },
    ),
    "Q3": TaskSpecification(
        "Q3",
        "What is the official price of the Luxury Cloud-Comfort Memory Foam Mattress, and what sizes are available?",
        (P1,),
        require_price=(P1,),
        require_exact_sizes=(P1,),
    ),
    "Q4": TaskSpecification(
        "Q4",
        "Does the Luxury Cloud-Comfort Memory Foam Mattress use an inner-spring construction and cost $1,299? If not, provide the correct information.",
        (P1,),
        required_concept_groups={P1: (("memory_foam",),)},
        require_price=(P1,),
        required_denials={
            P1: (RequiredDenial("concept", "inner_spring"), RequiredDenial("price", 1299))
        },
    ),
    "Q5": TaskSpecification(
        "Q5",
        "What materials and structural components are used in the Classic Harmony Spring Mattress?",
        (P2,),
        required_concept_groups={
            P2: (
                ("inner_spring",),
                ("plush_padding",),
                ("quilted_top",),
                ("reinforced_edges",),
                ("natural_cotton_cover",),
            )
        },
    ),
    "Q6": TaskSpecification(
        "Q6",
        "How does the Classic Harmony Spring Mattress provide comfort, durability, and moisture management?",
        (P2,),
        required_concept_groups={
            P2: (
                ("reinforced_edges", "sag_prevention"),
                ("plush_padding", "quilted_top"),
                ("moisture_wicking",),
            )
        },
    ),
    "Q7": TaskSpecification(
        "Q7",
        "What is the official price of the Classic Harmony Spring Mattress, and what sizes are available?",
        (P2,),
        require_price=(P2,),
        require_exact_sizes=(P2,),
    ),
    "Q8": TaskSpecification(
        "Q8",
        "Is the Classic Harmony Spring Mattress made from 100% natural latex and available in Twin and Full sizes? If not, provide the correct information.",
        (P2,),
        required_concept_groups={P2: (("inner_spring",),)},
        require_exact_sizes=(P2,),
        required_denials={P2: (RequiredDenial("concept", "natural_latex"),)},
    ),
    "Q9": TaskSpecification(
        "Q9",
        "What materials and structural components are used in the EcoGreen Hybrid Latex Mattress?",
        (P3,),
        required_concept_groups={
            P3: (("natural_latex",), ("pocketed_coils",), ("organic_cotton_cover",))
        },
    ),
    "Q10": TaskSpecification(
        "Q10",
        "How does the EcoGreen Hybrid Latex Mattress provide pressure relief, reduce motion transfer, and support customers with allergies?",
        (P3,),
        required_concept_groups={
            P3: (
                ("responsive_bouncy",),
                ("pressure_relief",),
                ("minimal_motion_transfer",),
                ("antimicrobial", "hypoallergenic"),
            )
        },
    ),
    "Q11": TaskSpecification(
        "Q11",
        "What is the official price of the EcoGreen Hybrid Latex Mattress, and what sizes are available?",
        (P3,),
        require_price=(P3,),
        require_exact_sizes=(P3,),
    ),
    "Q12": TaskSpecification(
        "Q12",
        "Does the EcoGreen Hybrid Latex Mattress have a bamboo-infused top layer and cost $2,599? If not, provide the correct information.",
        (P3,),
        required_concept_groups={
            P3: (("natural_latex",), ("pocketed_coils",), ("organic_cotton_cover",))
        },
        require_price=(P3,),
        required_denials={
            P3: (RequiredDenial("concept", "bamboo_top"), RequiredDenial("price", 2599))
        },
    ),
    "Q13": TaskSpecification(
        "Q13",
        "What materials and structural components are used in the Plush Serenity Bamboo Mattress?",
        (P4,),
        required_concept_groups={
            P4: (
                ("adaptive_foam",),
                ("high_resilience_support_foam",),
                ("bamboo_top",),
                ("removable_bamboo_cover",),
            )
        },
    ),
    "Q14": TaskSpecification(
        "Q14",
        "How does the Plush Serenity Bamboo Mattress provide tailored support, durability, temperature regulation, and moisture control?",
        (P4,),
        required_concept_groups={
            P4: (
                ("body_conforming", "tailored_support"),
                ("high_resilience_support_foam", "sag_prevention"),
                ("temperature_regulation", "cool_surface"),
                ("bamboo_breathability", "moisture_wicking"),
            )
        },
    ),
    "Q15": TaskSpecification(
        "Q15",
        "What is the official price of the Plush Serenity Bamboo Mattress, and what sizes are available?",
        (P4,),
        require_price=(P4,),
        require_exact_sizes=(P4,),
    ),
    "Q16": TaskSpecification(
        "Q16",
        "Is the Plush Serenity Bamboo Mattress available in Twin, Queen, and King sizes and priced at $999? If not, provide the correct information.",
        (P4,),
        require_price=(P4,),
        require_exact_sizes=(P4,),
        required_denials={P4: (RequiredDenial("price", 999),)},
    ),
}


STANDARD_REFERENCE_ANSWERS: dict[str, str] = {
    "Q1": "The Luxury Cloud-Comfort Memory Foam Mattress uses a temperature-sensitive memory foam layer, a high-density foam base, cooling gel-infused particles, and a breathable hypoallergenic cover embroidered with silver threads.",
    "Q2": "The temperature-sensitive memory foam conforms to the sleeper's body shape and provides personalized support. Cooling gel-infused particles regulate body temperature, while the high-density foam base improves durability. Its hypoallergenic cover helps keep allergens at bay.",
    "Q3": "Its official price is $999, and it is available in Twin, Queen, and King sizes.",
    "Q4": "No. The Luxury Cloud-Comfort Memory Foam Mattress uses memory foam and a high-density foam base, not an inner-spring construction. Its official price is $999, not $1,299.",
    "Q5": "The Classic Harmony Spring Mattress uses a robust inner-spring construction, layers of plush padding, a quilted top layer, reinforced edges, and a natural cotton cover.",
    "Q6": "Its inner-spring construction, plush padding, and quilted top provide support and comfort. Reinforced edges prevent sagging, while the natural cotton cover wicks away moisture.",
    "Q7": "Its official price is $1,299, and it is available in Queen and King sizes.",
    "Q8": "No. The Classic Harmony Spring Mattress uses an inner-spring construction, not natural latex. It is available in Queen and King sizes, not Twin and Full sizes.",
    "Q9": "The EcoGreen Hybrid Latex Mattress uses 100% natural latex layered over individually pocketed coils and has a certified organic cotton cover.",
    "Q10": "Its natural latex provides a responsive and bouncy feel together with pressure relief. The individually pocketed coils minimise motion transfer, while the antimicrobial and hypoallergenic properties of latex support allergy sufferers.",
    "Q11": "Its official price is $1,599, and it is available in Twin and Full sizes.",
    "Q12": "No. The EcoGreen Hybrid Latex Mattress uses natural latex, individually pocketed coils, and an organic cotton cover. It does not have a bamboo-infused top layer. Its official price is $1,599, not $2,599.",
    "Q13": "The Plush Serenity Bamboo Mattress uses plush adaptive foam, a high-resilience support foam base, a bamboo-infused top layer, and a silky removable bamboo cover.",
    "Q14": "Its adaptive foam molds to the sleeper's body and provides tailored support. The high-resilience support foam improves durability and prevents sagging. The bamboo-infused top layer creates a cool sleeping surface, while bamboo's natural breathability and moisture-wicking properties regulate temperature and moisture.",
    "Q15": "Its official price is $2,599, and it is available only in King size.",
    "Q16": "No. The Plush Serenity Bamboo Mattress is available only in King size, and its official price is $2,599, not $999.",
}


# ---------------------------------------------------------------------------
# Data contracts
# ---------------------------------------------------------------------------


@dataclass
class Span:
    start: int
    end: int
    text: str


@dataclass
class Proposition:
    proposition_id: str
    sentence_index: int
    span: Span
    product_id: Optional[str]
    attribute: Optional[str]
    value: Any
    polarity: str  # positive | negative
    value_kind: str  # product_name | concept | price | size | none


@dataclass
class LogicalEvent:
    rule_id: str
    category: str
    severity: str
    explanation: str
    evidence: list[Span]


@dataclass
class FactRecord:
    product_id: Optional[str]
    claim: str
    attribute: str
    generated_value: Any
    authorised_value: Any
    verification_result: str  # supported | contradicted | unsupported | omitted
    polarity: str
    evidence: list[Span]
    explanation: str


@dataclass
class DetectionContext:
    task_id: str
    model_id: str = "unknown-model"


@dataclass
class DetectionReport:
    task_id: str
    model_id: str
    catalogue_version: str
    question: str
    response: str
    propositions: list[Proposition]
    logical_status: int
    factual_status: int
    overall_status: int
    diagnostic_state: str
    logical_events: list[LogicalEvent]
    factual_records: list[FactRecord]
    counts: dict[str, int]

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


# ---------------------------------------------------------------------------
# Normalisation, sentence spans and claim polarity
# ---------------------------------------------------------------------------


_SPACE_RE = re.compile(r"[\t\r\f\v ]+")
_SENTENCE_RE = re.compile(r"[^.!?\n]+(?:[.!?]+|$)", re.MULTILINE)
_PRICE_RE = re.compile(
    r"\$\s*(\d{1,3}(?:,\d{3})+(?:\.\d{1,2})?|\d+(?:\.\d{1,2})?)"
)
_SIZE_RE = re.compile(r"\b(Twin|Queen|King|Full|Single|Double)\b", re.I)


def normalise_text(text: str) -> str:
    """Normalise punctuation and whitespace for deterministic processing."""
    text = text.replace("\u2018", "'").replace("\u2019", "'")
    text = text.replace("\u201c", '"').replace("\u201d", '"')
    text = text.replace("\u2013", "-").replace("\u2014", "-")
    lines = [_SPACE_RE.sub(" ", line).strip() for line in text.splitlines()]
    return "\n".join(line for line in lines if line)


def sentence_spans(text: str) -> list[Span]:
    spans: list[Span] = []
    for match in _SENTENCE_RE.finditer(text):
        raw = match.group(0)
        left = len(raw) - len(raw.lstrip())
        cleaned = raw.strip()
        if cleaned:
            start = match.start() + left
            spans.append(Span(start, start + len(cleaned), cleaned))
    return spans


def _last_boundary(prefix: str) -> int:
    boundaries = [
        prefix.rfind(mark) + len(mark)
        for mark in (".", "!", "?", ",", ";", ":", "\n")
    ]
    low = prefix.lower()
    for token in (" but ", " however ", " whereas ", " while ", " instead "):
        pos = low.rfind(token)
        if pos >= 0:
            boundaries.append(pos + len(token))
    return max(boundaries, default=0)


def _claim_polarity(sentence: str, claim_start: int) -> str:
    """Determine polarity from the local clause preceding one extracted claim.

    The clause boundary prevents a leading response such as ``No, it uses ...``
    from negating the corrective statement after the comma.  It also separates
    ``official value, not incorrect value`` into positive and negative claims.
    """
    prefix = sentence[:claim_start]
    scope = prefix[_last_boundary(prefix):].lower()
    scope = re.sub(r"\bnot\s+only\b", "", scope)
    negation = re.search(
        r"\b(?:not|never|without)\b|\b(?:does|do|did|is|are|was|were|has|have|had)\s+not\b|"
        r"\b(?:doesn't|don't|didn't|isn't|aren't|wasn't|weren't|hasn't|haven't|hadn't)\b|"
        r"\brather\s+than\b",
        scope,
    )
    return "negative" if negation else "positive"


def _price_value(raw: str) -> int:
    return int(round(float(raw.replace(",", ""))))


def _price_display(value: int) -> str:
    return f"${value:,}"


def _name_matches(sentence: Span) -> list[tuple[int, int, str, str]]:
    matches: list[tuple[int, int, str, str]] = []
    for product_id, product in PRODUCTS.items():
        for alias in (product.name,) + product.name_aliases:
            match = re.search(re.escape(alias), sentence.text, re.I)
            if match:
                matches.append((match.start(), match.end(), product_id, match.group(0)))
                break
    return sorted(matches)


def _resolve_product(
    local_start: int,
    name_matches: list[tuple[int, int, str, str]],
    task: TaskSpecification,
) -> Optional[str]:
    preceding = [item for item in name_matches if item[0] <= local_start]
    if preceding:
        return preceding[-1][2]
    if len(task.product_ids) == 1:
        return task.product_ids[0]
    return None


def extract_propositions(text: str, task: TaskSpecification) -> list[Proposition]:
    propositions: list[Proposition] = []
    for sentence_index, sentence in enumerate(sentence_spans(text)):
        names = _name_matches(sentence)
        before_count = len(propositions)

        for local_start, local_end, product_id, raw in names:
            span = Span(sentence.start + local_start, sentence.start + local_end, raw)
            propositions.append(
                Proposition(
                    f"P{len(propositions)+1}", sentence_index, span, product_id,
                    "product_name", product_id, _claim_polarity(sentence.text, local_start),
                    "product_name",
                )
            )

        for concept_key, definition in CONCEPTS.items():
            seen: set[tuple[int, int]] = set()
            for pattern in definition.patterns:
                for match in re.finditer(pattern, sentence.text, re.I):
                    # A product name is verified separately; words such as
                    # "Memory Foam", "Spring" or "Latex" inside the name do
                    # not by themselves satisfy a feature requirement.
                    if any(
                        name_start < match.end() and match.start() < name_end
                        for name_start, name_end, _, _ in names
                    ):
                        continue
                    if any(
                        seen_start < match.end() and match.start() < seen_end
                        for seen_start, seen_end in seen
                    ):
                        continue
                    seen.add((match.start(), match.end()))
                    product_id = _resolve_product(match.start(), names, task)
                    span = Span(
                        sentence.start + match.start(), sentence.start + match.end(), match.group(0)
                    )
                    propositions.append(
                        Proposition(
                            f"P{len(propositions)+1}", sentence_index, span, product_id,
                            definition.attribute, concept_key,
                            _claim_polarity(sentence.text, match.start()), "concept",
                        )
                    )

        for match in _PRICE_RE.finditer(sentence.text):
            product_id = _resolve_product(match.start(), names, task)
            span = Span(sentence.start + match.start(), sentence.start + match.end(), match.group(0))
            propositions.append(
                Proposition(
                    f"P{len(propositions)+1}", sentence_index, span, product_id,
                    "price", _price_value(match.group(1)),
                    _claim_polarity(sentence.text, match.start()), "price",
                )
            )

        for match in _SIZE_RE.finditer(sentence.text):
            product_id = _resolve_product(match.start(), names, task)
            value = match.group(1).title()
            span = Span(sentence.start + match.start(), sentence.start + match.end(), match.group(0))
            propositions.append(
                Proposition(
                    f"P{len(propositions)+1}", sentence_index, span, product_id,
                    "sizes", value, _claim_polarity(sentence.text, match.start()), "size",
                )
            )

        if len(propositions) == before_count:
            propositions.append(
                Proposition(
                    f"P{len(propositions)+1}", sentence_index, sentence, None,
                    None, None, "positive", "none",
                )
            )
    return propositions


# ---------------------------------------------------------------------------
# Layer 1: internal self-consistency detection (single response only)
# ---------------------------------------------------------------------------


MUTUAL_EXCLUSION_RULES: tuple[tuple[str, str, str], ...] = (
    ("L-STRUCT-01", "memory_foam", "inner_spring"),
    ("L-MATERIAL-01", "memory_foam", "natural_latex"),
    ("L-COOL-01", "cooling_gel", "heat_retaining_foam"),
    ("L-COVER-01", "silver_thread", "unembroidered_cover"),
    ("L-BASE-01", "high_density_foam_base", "thin_disposable_base"),
)


def internal_self_consistency_check(
    propositions: list[Proposition],
) -> tuple[int, list[LogicalEvent]]:
    events: list[LogicalEvent] = []
    positive_concepts = [
        prop for prop in propositions
        if prop.value_kind == "concept" and prop.polarity == "positive"
    ]

    for rule_id, left_key, right_key in MUTUAL_EXCLUSION_RULES:
        left = [prop for prop in positive_concepts if prop.value == left_key]
        right = [prop for prop in positive_concepts if prop.value == right_key]
        for left_prop in left:
            for right_prop in right:
                same_product = (
                    left_prop.product_id == right_prop.product_id
                    or left_prop.product_id is None
                    or right_prop.product_id is None
                )
                if same_product:
                    events.append(
                        LogicalEvent(
                            rule_id,
                            "mutually_exclusive_claims",
                            "high",
                            f"'{left_prop.span.text}' conflicts with '{right_prop.span.text}'.",
                            [left_prop.span, right_prop.span],
                        )
                    )
                    break

    # A response cannot assert two different positive prices for one product.
    product_ids = {prop.product_id for prop in propositions if prop.product_id}
    for product_id in product_ids:
        prices = [
            prop for prop in propositions
            if prop.product_id == product_id
            and prop.value_kind == "price"
            and prop.polarity == "positive"
        ]
        values = {prop.value for prop in prices}
        if len(values) > 1:
            events.append(
                LogicalEvent(
                    "L-VALUE-PRICE",
                    "inconsistent_attribute_values",
                    "high",
                    f"Multiple positive prices were asserted for {product_id}: "
                    f"{[_price_display(value) for value in sorted(values)]}.",
                    [prop.span for prop in prices],
                )
            )

    # The same exact claim cannot be both affirmed and denied.
    keyed: dict[tuple[Optional[str], str, str], list[Proposition]] = {}
    for prop in propositions:
        if prop.value_kind in {"concept", "price", "size", "product_name"}:
            keyed.setdefault((prop.product_id, prop.value_kind, str(prop.value)), []).append(prop)
    for (product_id, kind, value), claims in keyed.items():
        if {claim.polarity for claim in claims} == {"positive", "negative"}:
            events.append(
                LogicalEvent(
                    f"L-POLARITY-{kind.upper()}",
                    "contradictory_polarity",
                    "high",
                    f"The response both affirms and denies {kind}={value} for {product_id}.",
                    [claim.span for claim in claims],
                )
            )

    return int(bool(events)), events


# ---------------------------------------------------------------------------
# Layer 2: external authorised-knowledge verification
# ---------------------------------------------------------------------------


def _authorised_concepts_for_attribute(product: ProductKnowledge, attribute: str) -> list[str]:
    return sorted(
        key
        for key in product.authorised_concepts
        if CONCEPTS[key].attribute == attribute
    )


def _concept_display(keys: Iterable[str]) -> list[str]:
    return [CONCEPTS[key].canonical for key in keys]


def _target_product(prop: Proposition, task: TaskSpecification) -> Optional[str]:
    if prop.product_id:
        return prop.product_id
    if len(task.product_ids) == 1:
        return task.product_ids[0]
    return None


def _record_for_proposition(
    prop: Proposition, task: TaskSpecification
) -> Optional[FactRecord]:
    product_id = _target_product(prop, task)
    if prop.value_kind == "none":
        return None

    if prop.value_kind == "product_name":
        result = "supported" if product_id in task.product_ids and prop.polarity == "positive" else "contradicted"
        official = PRODUCTS[product_id].name if product_id in PRODUCTS else None
        explanation = (
            "The product name is authorised for this task."
            if result == "supported"
            else "The product-name claim conflicts with the task and catalogue."
        )
        return FactRecord(
            product_id, prop.span.text, "product_name", prop.span.text, official,
            result, prop.polarity, [prop.span], explanation,
        )

    if product_id not in PRODUCTS:
        return FactRecord(
            product_id, prop.span.text, prop.attribute or "unknown", prop.value, None,
            "unsupported", prop.polarity, [prop.span],
            "The claim could not be mapped to a target product.",
        )

    product = PRODUCTS[product_id]

    if prop.value_kind == "concept":
        concept_key = str(prop.value)
        authorised = concept_key in product.authorised_concepts
        if prop.polarity == "positive":
            result = "supported" if authorised else "contradicted"
            explanation = (
                "The product feature is supported by the official catalogue."
                if authorised
                else "The positive product-feature claim conflicts with the official catalogue."
            )
        else:
            result = "contradicted" if authorised else "supported"
            explanation = (
                "The response incorrectly denies an authorised product feature."
                if authorised
                else "The response correctly rejects a feature that is not authorised for this product."
            )
        alternatives = _concept_display(
            _authorised_concepts_for_attribute(product, CONCEPTS[concept_key].attribute)
        )
        return FactRecord(
            product_id,
            prop.span.text,
            CONCEPTS[concept_key].attribute,
            CONCEPTS[concept_key].canonical,
            alternatives,
            result,
            prop.polarity,
            [prop.span],
            explanation,
        )

    if prop.value_kind == "price":
        authorised = int(prop.value) == product.price
        if prop.polarity == "positive":
            result = "supported" if authorised else "contradicted"
            explanation = (
                "The stated price matches the official catalogue."
                if authorised
                else "The stated price conflicts with the official catalogue."
            )
        else:
            result = "contradicted" if authorised else "supported"
            explanation = (
                "The response incorrectly denies the official price."
                if authorised
                else "The response correctly rejects an incorrect price."
            )
        return FactRecord(
            product_id, prop.span.text, "price", _price_display(int(prop.value)),
            _price_display(product.price), result, prop.polarity, [prop.span], explanation,
        )

    if prop.value_kind == "size":
        official_sizes = set(product.sizes)
        authorised = str(prop.value) in official_sizes
        if prop.polarity == "positive":
            result = "supported" if authorised else "contradicted"
            explanation = (
                "The stated size is officially available."
                if authorised
                else "The stated size is not officially available for this product."
            )
        else:
            result = "contradicted" if authorised else "supported"
            explanation = (
                "The response incorrectly denies an officially available size."
                if authorised
                else "The response correctly rejects an unavailable size."
            )
        return FactRecord(
            product_id, prop.span.text, "sizes", prop.value, list(product.sizes),
            result, prop.polarity, [prop.span], explanation,
        )
    return None


def _overlaps_existing(start: int, end: int, propositions: list[Proposition]) -> bool:
    return any(
        prop.span.start < end and start < prop.span.end
        for prop in propositions
        if prop.value_kind != "none"
    )


def _required_denial_satisfied(
    denial: RequiredDenial,
    product_id: str,
    propositions: list[Proposition],
    task: TaskSpecification,
) -> bool:
    for prop in propositions:
        if _target_product(prop, task) != product_id:
            continue
        if prop.polarity != "negative":
            continue
        if denial.kind == "concept" and prop.value_kind == "concept" and prop.value == denial.value:
            return True
        if denial.kind == "price" and prop.value_kind == "price" and prop.value == denial.value:
            return True
        if denial.kind == "size" and prop.value_kind == "size" and prop.value == denial.value:
            return True
    return False


def external_knowledge_check(
    text: str,
    propositions: list[Proposition],
    task: TaskSpecification,
) -> tuple[int, list[FactRecord]]:
    records: list[FactRecord] = []

    for prop in propositions:
        record = _record_for_proposition(prop, task)
        if record:
            records.append(record)

    # Detect generic fabricated claims not represented by catalogue concepts.
    for category, patterns in GENERIC_UNSUPPORTED_CLAIMS.items():
        for pattern in patterns:
            for match in re.finditer(pattern, text, re.I):
                if _overlaps_existing(match.start(), match.end(), propositions):
                    continue
                polarity = _claim_polarity(text, match.start())
                product_id = task.product_ids[0] if len(task.product_ids) == 1 else None
                result = "unsupported" if polarity == "positive" else "supported"
                records.append(
                    FactRecord(
                        product_id,
                        match.group(0),
                        category,
                        match.group(0),
                        None,
                        result,
                        polarity,
                        [Span(match.start(), match.end(), match.group(0))],
                        (
                            "The positive claim is not authorised by the official catalogue."
                            if result == "unsupported"
                            else "The response correctly rejects a claim absent from the catalogue."
                        ),
                    )
                )

    # Required catalogue product names (Q1).
    for product_id in task.require_product_names:
        found = any(
            prop.value_kind == "product_name"
            and prop.product_id == product_id
            and prop.polarity == "positive"
            for prop in propositions
        )
        if not found:
            records.append(
                FactRecord(
                    product_id, "", "product_name", None, PRODUCTS[product_id].name,
                    "omitted", "positive", [],
                    "The task requires this catalogue product name, but it is absent.",
                )
            )

    # Required feature groups: at least one authorised positive concept from
    # each group must be present.
    for product_id, groups in task.required_concept_groups.items():
        for group in groups:
            found = any(
                _target_product(prop, task) == product_id
                and prop.value_kind == "concept"
                and prop.polarity == "positive"
                and prop.value in group
                and prop.value in PRODUCTS[product_id].authorised_concepts
                for prop in propositions
            )
            if not found:
                records.append(
                    FactRecord(
                        product_id,
                        "",
                        CONCEPTS[group[0]].attribute,
                        None,
                        _concept_display(group),
                        "omitted",
                        "positive",
                        [],
                        "A task-required catalogue feature is absent from the response.",
                    )
                )

    # Required official price.
    for product_id in task.require_price:
        positive_price_claims = [
            prop
            for prop in propositions
            if _target_product(prop, task) == product_id
            and prop.value_kind == "price"
            and prop.polarity == "positive"
        ]
        found = any(
            _target_product(prop, task) == product_id
            and prop.value_kind == "price"
            and prop.polarity == "positive"
            and prop.value == PRODUCTS[product_id].price
            for prop in propositions
        )
        # An incorrect positive price is already classified as contradicted;
        # add omission only when no positive price was supplied at all.
        if not found and not positive_price_claims:
            records.append(
                FactRecord(
                    product_id, "", "price", None, _price_display(PRODUCTS[product_id].price),
                    "omitted", "positive", [],
                    "The task requires the official price, but it is absent.",
                )
            )

    # Tasks that ask for all sizes require exact positive coverage.  Correctly
    # denied unavailable sizes do not count as positive sizes.
    for product_id in task.require_exact_sizes:
        positive_sizes = {
            str(prop.value)
            for prop in propositions
            if _target_product(prop, task) == product_id
            and prop.value_kind == "size"
            and prop.polarity == "positive"
        }
        for missing in set(PRODUCTS[product_id].sizes) - positive_sizes:
            records.append(
                FactRecord(
                    product_id, "", "sizes", None, missing, "omitted", "positive", [],
                    f"The task requires the complete official size set; {missing} is absent.",
                )
            )

    # Misleading-premise questions require explicit correction of selected
    # false claims, not merely a generic 'No'.
    for product_id, denials in task.required_denials.items():
        for denial in denials:
            if not _required_denial_satisfied(denial, product_id, propositions, task):
                authorised_value: Any = denial.value
                if denial.kind == "concept":
                    authorised_value = f"explicit rejection of {CONCEPTS[str(denial.value)].canonical}"
                elif denial.kind == "price":
                    authorised_value = f"explicit rejection of {_price_display(int(denial.value))}"
                records.append(
                    FactRecord(
                        product_id,
                        "",
                        f"required_{denial.kind}_correction",
                        None,
                        authorised_value,
                        "omitted",
                        "negative",
                        [],
                        "The response does not explicitly correct one of the question's false premises.",
                    )
                )

    error_results = {"contradicted", "unsupported", "omitted"}
    factual_status = int(any(record.verification_result in error_results for record in records))
    return factual_status, records


# ---------------------------------------------------------------------------
# Dual-layer fusion and public API
# ---------------------------------------------------------------------------


def _diagnostic_state(logical: int, factual: int) -> str:
    return {
        (0, 0): "no_detected_hallucination",
        (1, 0): "logical_hallucination_only",
        (0, 1): "factual_hallucination_only",
        (1, 1): "combined_logical_and_factual_hallucination",
    }[(logical, factual)]


def detect_hallucination(
    task_id: str,
    model_answer: str,
    model_id: str = "unknown-model",
    question: Optional[str] = None,
) -> DetectionReport:
    task_id = task_id.upper()
    if task_id not in TASK_SPECIFICATIONS:
        raise ValueError(f"Unknown task_id {task_id!r}; expected Q1-Q16.")
    task = TASK_SPECIFICATIONS[task_id]
    normalised = normalise_text(model_answer)
    propositions = extract_propositions(normalised, task)
    logical_status, logical_events = internal_self_consistency_check(propositions)
    factual_status, factual_records = external_knowledge_check(normalised, propositions, task)
    overall_status = int(bool(logical_status or factual_status))
    counts = {
        "logical_events": len(logical_events),
        "supported_records": sum(r.verification_result == "supported" for r in factual_records),
        "contradicted_records": sum(r.verification_result == "contradicted" for r in factual_records),
        "unsupported_records": sum(r.verification_result == "unsupported" for r in factual_records),
        "omitted_records": sum(r.verification_result == "omitted" for r in factual_records),
    }
    return DetectionReport(
        task_id,
        model_id,
        CATALOGUE_VERSION,
        question or task.question,
        normalised,
        propositions,
        logical_status,
        factual_status,
        overall_status,
        _diagnostic_state(logical_status, factual_status),
        logical_events,
        factual_records,
        counts,
    )


def print_report(report: DetectionReport, show_text: bool = True) -> None:
    print("===== Simple-Dual RD1 Detection Report =====")
    print(f"Task / Model: {report.task_id} / {report.model_id}")
    if show_text:
        print(f"Question: {report.question}")
        print(f"Response: {report.response}")
    print(f"Logical status: {report.logical_status}")
    for event in report.logical_events:
        print(f"  - [{event.rule_id}; {event.severity}] {event.explanation}")
    print(f"Factual status: {report.factual_status}")
    for record in report.factual_records:
        if record.verification_result != "supported":
            print(
                f"  - [{record.verification_result}] {record.product_id} / "
                f"{record.attribute}: {record.explanation}"
            )
    print(f"Overall status: {report.overall_status} ({report.diagnostic_state})")


# ---------------------------------------------------------------------------
# Automatic 64-response batch experiment
# ---------------------------------------------------------------------------


def _safe_div(numerator: int, denominator: int) -> float:
    return numerator / denominator if denominator else 0.0


def _summarise_reports(reports: list[DetectionReport]) -> dict[str, Any]:
    def summarise(items: list[DetectionReport]) -> dict[str, Any]:
        total = len(items)
        detected = sum(report.overall_status for report in items)
        return {
            "records": total,
            "detected_responses": detected,
            "hallucination_free_responses": total - detected,
            "detection_rate": _safe_div(detected, total),
            "logical_detected_responses": sum(report.logical_status for report in items),
            "factual_detected_responses": sum(report.factual_status for report in items),
            "combined_detected_responses": sum(
                report.logical_status == 1 and report.factual_status == 1 for report in items
            ),
            "logical_events": sum(report.counts["logical_events"] for report in items),
            "supported_records": sum(report.counts["supported_records"] for report in items),
            "contradicted_records": sum(report.counts["contradicted_records"] for report in items),
            "unsupported_records": sum(report.counts["unsupported_records"] for report in items),
            "omitted_records": sum(report.counts["omitted_records"] for report in items),
        }

    model_ids = sorted({report.model_id for report in reports})
    task_ids = sorted({report.task_id for report in reports}, key=lambda value: int(value[1:]))
    return {
        "overall": summarise(reports),
        "by_model": {
            model_id: summarise([report for report in reports if report.model_id == model_id])
            for model_id in model_ids
        },
        "by_task": {
            task_id: summarise([report for report in reports if report.task_id == task_id])
            for task_id in task_ids
        },
    }


def validate_experimental_grid(
    reports: list[DetectionReport],
    model_ids: tuple[str, ...] = MODEL_IDS,
) -> dict[str, Any]:
    expected = {(task_id, model_id) for task_id in TASK_SPECIFICATIONS for model_id in model_ids}
    observed_pairs = [(report.task_id, report.model_id) for report in reports]
    observed = set(observed_pairs)
    duplicates = sorted({pair for pair in observed_pairs if observed_pairs.count(pair) > 1})
    missing = sorted(expected - observed, key=lambda pair: (int(pair[0][1:]), pair[1]))
    unexpected = sorted(observed - expected)
    return {
        "valid": not missing and not duplicates and not unexpected and len(reports) == 64,
        "expected_records": 64,
        "observed_records": len(reports),
        "missing_pairs": [list(pair) for pair in missing],
        "duplicate_pairs": [list(pair) for pair in duplicates],
        "unexpected_pairs": [list(pair) for pair in unexpected],
    }


def run_batch_csv(
    input_csv: Path,
    output_jsonl: Path,
    require_complete_grid: bool = False,
) -> dict[str, Any]:
    """Run automatic RD1 detection over CSV records.

    Required columns: ``task_id``, ``model_id`` and ``response``.
    The optional ``question`` column overrides the registered question text.
    Additional evaluation-label columns are neither required nor used.
    """
    reports: list[DetectionReport] = []
    with input_csv.open("r", encoding="gb18030", newline="") as handle:
        reader = csv.DictReader(handle)
        required_columns = {"task_id", "model_id", "response"}
        if not reader.fieldnames or not required_columns.issubset(reader.fieldnames):
            raise ValueError(
                f"CSV must contain columns {sorted(required_columns)}; got {reader.fieldnames}."
            )
        for row_number, row in enumerate(reader, start=2):
            task_id = (row.get("task_id") or "").strip().upper()
            model_id = (row.get("model_id") or "").strip()
            response = row.get("response") or ""
            if not task_id or not model_id:
                raise ValueError(f"Missing task_id or model_id on CSV row {row_number}.")
            reports.append(
                detect_hallucination(
                    task_id,
                    response,
                    model_id=model_id,
                    question=(row.get("question") or "").strip() or None,
                )
            )

    output_jsonl.parent.mkdir(parents=True, exist_ok=True)
    with output_jsonl.open("w", encoding="utf-8") as handle:
        for report in reports:
            handle.write(json.dumps(report.to_dict(), ensure_ascii=False) + "\n")

    grid = validate_experimental_grid(reports)
    if require_complete_grid and not grid["valid"]:
        raise ValueError(f"The batch is not the required complete 64-response grid: {grid}")
    return {
        "catalogue_version": CATALOGUE_VERSION,
        "output": str(output_jsonl),
        "grid_validation": grid,
        "automatic_summary": _summarise_reports(reports),
    }


def write_batch_template(output_csv: Path) -> None:
    """Write the fixed 64-row Q1-Q16 x four-model experiment template."""
    output_csv.parent.mkdir(parents=True, exist_ok=True)
    with output_csv.open("w", encoding="utf-8-sig", newline="") as handle:
        writer = csv.DictWriter(
            handle, fieldnames=["task_id", "model_id", "question", "response"]
        )
        writer.writeheader()
        for task_id, task in TASK_SPECIFICATIONS.items():
            for model_id in MODEL_IDS:
                writer.writerow(
                    {
                        "task_id": task_id,
                        "model_id": model_id,
                        "question": task.question,
                        "response": "",
                    }
                )


# ---------------------------------------------------------------------------
# Deterministic self-test
# ---------------------------------------------------------------------------


def run_self_test() -> dict[str, Any]:
    failures: list[str] = []
    reference_results: dict[str, dict[str, int]] = {}
    for task_id, answer in STANDARD_REFERENCE_ANSWERS.items():
        report = detect_hallucination(task_id, answer, model_id="reference-answer")
        reference_results[task_id] = {
            "logical_status": report.logical_status,
            "factual_status": report.factual_status,
            "overall_status": report.overall_status,
        }
        if report.overall_status != 0:
            failures.append(f"{task_id} reference answer was not accepted: {report.to_dict()}")

    targeted_cases = {
        "correct_negation": (
            "Q4",
            "No. It uses memory foam and does not contain an inner-spring construction. "
            "Its official price is $999, not $1,299.",
            0,
        ),
        "logical_conflict": (
            "Q1",
            "It uses memory foam and an inner-spring construction, with a high-density "
            "foam base, cooling gel, a breathable hypoallergenic cover, and silver threads.",
            1,
        ),
        "wrong_product2_price": (
            "Q7", "Its official price is $999, and it is available in Queen and King sizes.", 1
        ),
        "incomplete_product1_sizes": (
            "Q3", "Its official price is $999, and it is available in Twin and Queen sizes.", 1
        ),
    }
    targeted_results: dict[str, int] = {}
    for name, (task_id, answer, expected_overall) in targeted_cases.items():
        report = detect_hallucination(task_id, answer, model_id="self-test")
        targeted_results[name] = report.overall_status
        if report.overall_status != expected_overall:
            failures.append(
                f"{name} expected overall={expected_overall}, got {report.overall_status}: "
                f"{report.to_dict()}"
            )

    return {
        "passed": not failures,
        "reference_answers_tested": len(reference_results),
        "reference_results": reference_results,
        "targeted_results": targeted_results,
        "failures": failures,
    }


def run_reference_answer_evaluation(
    print_details: bool = True,
    print_summary: bool = True,
) -> tuple[list[DetectionReport], dict[str, Any]]:
    """Evaluate and optionally display all sixteen standard reference answers."""
    reports: list[DetectionReport] = []
    if print_details:
        print("\n===== Q1-Q16 Standard Reference Answer Evaluation =====")
    for index, task_id in enumerate(TASK_SPECIFICATIONS, start=1):
        report = detect_hallucination(
            task_id,
            STANDARD_REFERENCE_ANSWERS[task_id],
            model_id="standard-reference-answer",
        )
        reports.append(report)
        if print_details:
            print(f"\n----- Reference answer {index}/16 -----")
            print_report(report, show_text=True)

    summary = _summarise_reports(reports)["overall"]
    if print_summary:
        print("\n===== Q1-Q16 Reference Evaluation Summary =====")
        print(f"Total questions: {summary['records']}")
        print(f"Hallucination-free answers: {summary['hallucination_free_responses']}")
        print(f"Detected answers: {summary['detected_responses']}")
        print(f"Logical detected answers: {summary['logical_detected_responses']}")
        print(f"Factual detected answers: {summary['factual_detected_responses']}")
        print(f"Overall detection rate: {summary['detection_rate']:.4f}")
    return reports, summary


def _read_answer_argument(answer: Optional[str], answer_file: Optional[Path]) -> str:
    if answer_file is not None:
        if not answer_file.exists():
            raise FileNotFoundError(f"Answer file does not exist: {answer_file}")
        return answer_file.read_text(encoding="utf-8-sig").strip()
    if answer is not None:
        return answer.strip()
    raise ValueError("A model answer must be supplied with --answer or --answer-file.")


def run_pycharm_mode() -> None:
    """Run the selected top-level configuration without command-line arguments.

    This entry point is intended for the normal PyCharm workflow: edit the
    ``PYCHARM_*`` constants near the top of this file and click Run.
    """
    mode = PYCHARM_MODE.strip().upper()

    if mode == "REFERENCE_16":
        run_reference_answer_evaluation(print_details=True, print_summary=True)
        return

    if mode == "SINGLE":
        configured_file = PYCHARM_ANSWER_FILE.strip()
        answer_file = Path(configured_file).expanduser() if configured_file else None
        answer = _read_answer_argument(PYCHARM_MODEL_ANSWER, answer_file)
        if not answer:
            raise ValueError(
                "PYCHARM_MODEL_ANSWER is empty. Paste the generated model answer "
                "between the triple quotes, or configure PYCHARM_ANSWER_FILE."
            )
        report = detect_hallucination(
            PYCHARM_TASK_ID,
            answer,
            model_id=PYCHARM_MODEL_ID,
        )
        print_report(report, show_text=True)
        return

    if mode == "CREATE_TEMPLATE":
        template_path = Path(PYCHARM_TEMPLATE_PATH).expanduser()
        write_batch_template(template_path)
        print("\n===== Simple-Dual RD1 CSV Template Created =====")
        print(f"File: {template_path.resolve()}")
        print("Rows: 64 (Q1-Q16 x four models)")
        return

    if mode == "BATCH":
        batch_path = Path(PYCHARM_BATCH_CSV_PATH).expanduser()
        output_path = Path(PYCHARM_BATCH_OUTPUT_PATH).expanduser()
        summary = run_batch_csv(
            batch_path,
            output_path,
            require_complete_grid=PYCHARM_REQUIRE_COMPLETE_GRID,
        )
        print("\n===== Simple-Dual RD1 Batch Summary =====")
        print(json.dumps(summary, ensure_ascii=False, indent=2))
        return

    if mode == "SELF_TEST":
        result = run_self_test()
        print("\n===== Simple-Dual RD1 Self-Test =====")
        print(json.dumps(result, ensure_ascii=False, indent=2))
        if not result["passed"]:
            raise AssertionError("Simple-Dual self-test failed; see failures above.")
        return

    allowed_modes = "REFERENCE_16, SINGLE, CREATE_TEMPLATE, BATCH, SELF_TEST"
    raise ValueError(
        f"Unknown PYCHARM_MODE: {PYCHARM_MODE!r}. Choose one of: {allowed_modes}."
    )


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Simple-Dual final RD1 single-turn hallucination detector"
    )
    parser.add_argument("--batch-csv", type=Path, help="Run a Q1-Q16 response CSV")
    parser.add_argument(
        "--output", type=Path, default=Path("simple_dual_rd1_results.jsonl")
    )
    parser.add_argument(
        "--require-complete-grid",
        action="store_true",
        help="Require exactly one response for every Q1-Q16 x four-model pair",
    )
    parser.add_argument("--write-template", type=Path, help="Write the 64-row CSV template")
    parser.add_argument("--self-test", action="store_true", help="Run deterministic tests")
    parser.add_argument(
        "--reference-test",
        action="store_true",
        help="Display detection results for all Q1-Q16 standard answers",
    )
    parser.add_argument(
        "--task-id",
        type=str,
        help="Evaluate one generated answer using Q1-Q16, for example Q4",
    )
    answer_group = parser.add_mutually_exclusive_group()
    answer_group.add_argument("--answer", type=str, help="Generated answer text")
    answer_group.add_argument(
        "--answer-file",
        type=Path,
        help="UTF-8 text file containing one generated answer",
    )
    parser.add_argument(
        "--model-id",
        type=str,
        default="unknown-model",
        help="Model name recorded in a single-answer report",
    )
    parser.add_argument(
        "--question",
        type=str,
        help="Optional question override for a single-answer report",
    )
    parser.add_argument("--json", action="store_true", help="Print machine-readable JSON")
    args = parser.parse_args()

    if args.write_template:
        write_batch_template(args.write_template)
        print(json.dumps({"template": str(args.write_template), "records": 64}, indent=2))
        return
    if args.self_test:
        result = run_self_test()
        print(json.dumps(result, ensure_ascii=False, indent=2))
        raise SystemExit(0 if result["passed"] else 1)
    if args.batch_csv:
        summary = run_batch_csv(
            args.batch_csv, args.output, require_complete_grid=args.require_complete_grid
        )
        print(json.dumps(summary, ensure_ascii=False, indent=2))
        return
    if args.task_id:
        answer = _read_answer_argument(args.answer, args.answer_file)
        report = detect_hallucination(
            args.task_id,
            answer,
            model_id=args.model_id,
            question=args.question,
        )
        if args.json:
            print(json.dumps(report.to_dict(), ensure_ascii=False, indent=2))
        else:
            print_report(report, show_text=True)
        return
    if args.answer is not None or args.answer_file is not None:
        parser.error("--answer and --answer-file require --task-id Q1-Q16")

    # With no arguments, show the complete Q1-Q16 standard-answer evaluation.
    reports, summary = run_reference_answer_evaluation(
        print_details=not args.json,
        print_summary=not args.json,
    )
    if args.json:
        print(
            json.dumps(
                {
                    "reports": [report.to_dict() for report in reports],
                    "summary": summary,
                },
                ensure_ascii=False,
                indent=2,
            )
        )


if __name__ == "__main__":
    # PyCharm's green Run button normally starts the file without arguments.
    # Explicit command-line arguments continue to use the original CLI.
    if len(sys.argv) == 1:
        run_pycharm_mode()
    else:
        main()
